name: FModel QA Builder

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: .NET 8 Setup
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: .NET Restore
        run: dotnet restore "./FModel/FModel.slnx" -r win-x64

      - name: .NET Publish
        run: dotnet publish "./FModel/FModel.csproj" -c Release --no-restore --no-self-contained -r win-x64 -f net8.0-windows -o "./FModel/bin/Publish/" -p:PublishReadyToRun=false -p:PublishSingleFile=true -p:DebugType=None -p:GenerateDocumentationFile=false -p:DebugSymbols=false

      - name: 📦 Create ZIP archive
        run: |
          Compress-Archive -Path ./FModel/bin/Publish/FModel.exe -DestinationPath FModel-dev-${{ github.sha }}.zip

      - name: 📤 Upload as Workflow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FModel-dev-build
          path: FModel-dev-${{ github.sha }}.zip
          retention-days: 60  # 默认保留 90 天，这里设为 7 节省空间（可选）
